name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - run: npx playwright install --with-deps

      # Start Netlify Dev (builds, serves dist, and runs functions)
      - run: npx netlify dev -c "npm run build" --port 8888 --dir dist --functions netlify/functions & echo $! > .netlify.pid

      # Wait for healthz to come up (simple curl loop)
      - run: |
          for i in {1..30}; do
            curl -sf http://localhost:8888/.netlify/functions/healthz && break
            sleep 1
          done

      - run: BASE_URL=http://localhost:8888 npm run test:smoke

      - run: kill $(cat .netlify.pid) || true
